# Generated by Django 5.1.4 on 2024-12-04 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cattle',
            fields=[
                ('cattle_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('health_status', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('farmer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Veterinary',
            fields=[
                ('vet_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('specialization', models.CharField(max_length=200)),
                ('location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('disease', models.CharField(max_length=200)),
                ('symptoms', models.TextField()),
                ('treatment', models.TextField()),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_records', to='app_name.cattle')),
            ],
        ),
        migrations.AddField(
            model_name='cattle',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cattle', to='app_name.farmer'),
        ),
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('listing_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_listings', to='app_name.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='MilkProduction',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('milk_yield', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_productions', to='app_name.cattle')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('purpose', models.TextField()),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='app_name.cattle')),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='app_name.veterinary')),
            ],
        ),
    ]
